[package]
name = "camouflage-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "camouflage-tui"
path = "src/main.rs"

[[bin]]
name = "camouflage-diff"
path = "src/bin/camouflage_diff.rs"

[dependencies]
camouflage-protocol = { workspace = true }
camouflage-store = { workspace = true }
camouflage-renderer = { workspace = true }
camouflage-headless = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }
unicode-width = { workspace = true }
