[package]
name = "camouflage-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camouflage-protocol = { workspace = true }
rusqlite = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
